spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/battletechSearch
    username: adam9500
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect